-- Initial schema migration.
-- Replace this with your actual initial schema.
--
-- Guidelines:
--   UUID primary keys:     id UUID PRIMARY KEY DEFAULT gen_random_uuid()
--   Timestamps:            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
--   Strings:               TEXT (not VARCHAR)
--   Soft deletes:          deleted_at TIMESTAMPTZ
--   Foreign key indexes:   CREATE INDEX IF NOT EXISTS idx_table_col ON table(col)

-- Example:
-- CREATE TABLE IF NOT EXISTS items (
--     id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
--     name       TEXT        NOT NULL,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );
